# Generated by Django 2.1.5 on 2019-02-24 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190217_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.CharField(db_index=True, default=1, max_length=150),
            preserve_default=False,
        ),
    ]
