# Generated by Django 2.1.7 on 2019-03-02 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20190302_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.TextField(blank=True, max_length=3000),
        ),
        migrations.AlterField(
            model_name='tag',
            name='author',
            field=models.CharField(default='anonamuse', max_length=150),
        ),
    ]
